# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\"P\n\x04\x42ook\x12\x0c\n\x04ISBN\x18\x01 \x02(\t\x12\r\n\x05title\x18\x02 \x02(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x02(\t\x12\r\n\x05genre\x18\x04 \x03(\t\x12\x0c\n\x04year\x18\x05 \x02(\x05\"W\n\rInventoryItem\x12\x0e\n\x06number\x18\x01 \x02(\x05\x12\x15\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x05.BookH\x00\x12\x17\n\x06status\x18\x03 \x02(\x0e\x32\x07.StatusB\x06\n\x04type\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04ISBN\x18\x01 \x02(\t*\"\n\x06Status\x12\r\n\tavailable\x10\x00\x12\t\n\x05taken\x10\x01\x32Q\n\x10InventoryService\x12\x1a\n\nCreateBook\x12\x05.Book\x1a\x05.Book\x12!\n\x07GetBook\x12\x0f.GetBookRequest\x1a\x05.Book')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=222
  _STATUS._serialized_end=256
  _BOOK._serialized_start=19
  _BOOK._serialized_end=99
  _INVENTORYITEM._serialized_start=101
  _INVENTORYITEM._serialized_end=188
  _GETBOOKREQUEST._serialized_start=190
  _GETBOOKREQUEST._serialized_end=220
  _INVENTORYSERVICE._serialized_start=258
  _INVENTORYSERVICE._serialized_end=339
# @@protoc_insertion_point(module_scope)
